//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSRSSendMailService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSRSEmail
    {
        public int Id { get; set; }
        public string tieu_de { get; set; }
        public string noi_dung { get; set; }
        public string nguoi_gui { get; set; }
        public string nguoi_nhan { get; set; }
        public Nullable<System.DateTime> thoi_gian_gui { get; set; }
        public string trang_thai { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string CreatedBy { get; set; }
    }
}
